### ISSUE TITLE
Make CAW work with WES

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#191]

**Comment by marcelm** [comment]
Is this about whole exome sequencing? (The more common abbreviation for that would be WES.)

We had a customer this morning in the bioinformatics drop-in who is trying to use CAW on whole-exome data. Would be nice if this worked.

**Comment by MaxUlysse** [comment]
That was it, and it should work well since you provided the possibility to define intervals with bed files.
@szilvajuhos ran some exome data, he should be able to tell if it's fully working or need some more tinkering.

**Comment by szilvajuhos** [comment]
It is working in a way that one have to do everything just like at WGS, and filter the results from targeted regions. Tried to add the target BED, but that kills the whole stuff for many reasons (250K regions, 250K processes; most of them has no  result lines in the VCF etc.)

**Comment by marcelm** [comment]
Ok, thanks. Some of that should be fixed now that small target intervals are merged (so no 250K processes any longer).

**Comment by yafeng** [comment]
Great! You are working on it. Thanks to the help from @marcelm,  now I am able to run it on our local cluster.

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make CAW work with WES](https://trello.com/c/ObebZI8o/31-make-caw-work-with-wes)

**Comment by yafeng** [comment]
Hej, I want to ask a question here.
What is the consequence of using CAW pipeline for WES data?
The major steps are quite similar to me. Is the alignment step using different parameters?
I appreciate a lot for any comments!

**Comment by szilvajuhos** [comment]
Hej, you can use it for WES, the general recommendation is to use it as for WGS, and once the VCF files are ready, use only calls that are falling to the targeted regions.
