### ISSUE TITLE
Update dbSNP and COSMIC

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/Sarek#204]
- [ ] update dbSNP
~~- [ ] update COSMIC~~

Both needs access to the ToolBox directory, and we need the  help from UPPMAX support on bianca

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update dbSNP and COSMIC](https://trello.com/c/4JLLDP2U/30-update-dbsnp-and-cosmic)

**Comment by MaxUlysse** [comment]
Falls into iGenomes territory now
