### ISSUE TITLE
Use the HaplotypeCaller calls QC metrics

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/Sarek#205]
In the HaplotypeCaller calls we can check the common SNPs whether the two are the same: it can serve as a QC metric, i.e.to make sure the patients are not mixed up

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use the HaplotypeCaller calls QC metrics](https://trello.com/c/YibFg3Nt/29-use-the-haplotypecaller-calls-qc-metrics)

**Comment by MaxUlysse** [comment]
Transferred to the new [nf-core/sarek](https://github.com/nf-core/sarek/) repo
