### ISSUE TITLE
Optionally use samblaster for duplicate marking

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/Sarek#242]
See https://www.ncbi.nlm.nih.gov/pubmed/24812344 . It’s very easy to use, just pipe `bwa mem` output through `samblaster`.

**Comment by marcelm** [comment]
It’s not in the documentation for samblaster, but we need to be careful when a library was sequenced on multiple lanes. If there is only a single lane, then piping `bwa mem` into `samblaster` works, but otherwise, `samblaster` needs to be fed the full library, so some kind of merging is required just like now with MarkDuplicates.

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use samblaster for duplicate marking (optionnaly)](https://trello.com/c/tdnnfxay/28-use-samblaster-for-duplicate-marking-optionnaly)

**Comment by MaxUlysse** [comment]
Closing it, we'll see if the need for that arise within the new [nf-core/sarek](https://github.com/nf-core/sarek/) repo
