### ISSUE TITLE
Copy results even if Ascat fails

### ISSUE THREAD

**Issue by malinlarsson** [SciLifeLab/Sarek#289]
In some cases ASCAT fails to create a model for tumor purity and average ploidy. I have seen this in one case so far, but it is known that it happens for a certain fraction of tumors that are particularly complicated to assess. 
In such cases it would be good if part of the output from "runAscat" is still copied to the VariantCalling/Ascat folder. For example, the plots of raw data (xxx.tumor.png) and segmented data (xxx.ASPCF.png). This is useful information, especially together with a note that "ascat failed to find an estimation of average ploidy and purity").

**Comment by MaxUlysse** [comment]
Do you think it could be fixed by getting all files in the output channel, using `file("${idSampleTumor}.*.png"), file("${idSampleTumor}.*.txt")` ?

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Copy results even if Ascat fails](https://trello.com/c/578FH3TC/27-copy-results-even-if-ascat-fails)

**Comment by MaxUlysse** [comment]
We will reopen it if needed.
