### ISSUE TITLE
Parallelize indel realignment

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/Sarek#358]
Indel realignment could be split up by chromosomes or intervals. There would be additional BAM splitting and merging steps, so possibly the gains are low.

Anyway, we should first investigate whether indel realignment could be skipped entirely (#61).

Moved here from #267.

**Comment by ansluk** [comment]
One should perhaps also consider the vunerability of long jobs. Having jobs run for 10d+ on bianca has been difficult and the loss is substantial when an indel realignment terminates with NODE_FAILURE after 13 days.

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Parallelize indel realignment](https://trello.com/c/XCbjMOpk/23-parallelize-indel-realignment)

**Comment by apeltzer** [comment]
If you follow the BP #503  in GATK 4.0, this should not be required anymore IIRC.

**Comment by MaxUlysse** [comment]
cf #61
