### ISSUE TITLE
Update ASCAT to 2.5

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#407]
We're using 2.3, I do think it could be a good thing to try the new version at some point.

Could be related to #388

**Comment by szilvajuhos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ASCAT issues](https://trello.com/c/tmD2UJxW/1-ascat-issues)

**Comment by malinlarsson** [comment]
I'm not sure if this update is relevant for CAW at this point. According to the brief documentation (just a note), the update added multi-sample segmentation for samples that are expected to share breakpoints. We analyse one sample at a time in CAW, so do we need this feature? 
It seems that to use the feature we would have to redesign how we use Ascat (i.e. sending in primary tumor and relaps into the same process). Or am I thinking wrongly?

**Comment by szilvajuhos** [comment]
We can feed normal-tumour-relapse samples already, so it would be worth a try.

**Comment by malinlarsson** [comment]
OK, I agree that it would be nice to have. But we would have to modify the process RunAscat so that it takes all tumor samples at once, and we would have to rewrite the bin/run_ascat.r script.

**Comment by MaxUlysse** [comment]
> Add gc correction to ASCAT.
> Also, set gamma to 1 in ASCAT run.

**Comment by MaxUlysse** [comment]
Working actively on it on [nf-core/sarek](https://github.com/nf-core/sarek/), so no longer an issue
