### ISSUE TITLE
Final delivery checks

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/Sarek#448]
We are delivering variant calls and annotations at the very end. We have to have a final step/util to check all the VCF/annotation/QC/alignment files are there.

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check the final delivery files](https://trello.com/c/sAxVLNsi/18-check-the-final-delivery-files)

**Comment by MaxUlysse** [comment]
Transferred to the new [nf-core/sarek](https://github.com/nf-core/sarek/) repo
