### ISSUE TITLE
Qualimap BamQC container seems to have trouble on Bianca 

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#484]
Process is hanging forever.
I inspected the container on `bianca` and it seems to be working AFAIK.
Don't really understand the problem at the moment, will trying to figure out what's causing that...

**Comment by marcelm** [comment]
Can you SSH into the node, run `ps faxww` and paste the result here next time you see the problem? Would be interesting to see whether this is the same problem as #420.

**Comment by MaxUlysse** [comment]
So the container itself is hanging forever on `bianca`, I tried the `1.2.3`, the `1.2.1` and the `1.2` on one of our two projects, and none of them are working for me.
```bash
#Launching the container
/qualimap-1.2.3.img 
# In the container
$ qualimap bamqc -bam 1234N.recal.bam -outdir 1234N
Java memory size is set to 1200M
Launching application...

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
QualiMap v.2.2.1
Built on 2016-10-03 18:14

Selected tool: bamqc
Available memory (Mb): 32
Max memory (Mb): 1216
Starting bam qc....
Loading sam header...
Loading locator...
Loading reference...
Number of windows: 400, effective number of windows: 485
Chunk of reads size: 1000
Number of threads: 1
Processed 50 out of 485 windows...
Processed 100 out of 485 windows...
Processed 150 out of 485 windows...
Processed 200 out of 485 windows...
Processed 250 out of 485 windows...
Processed 300 out of 485 windows...
Processed 350 out of 485 windows...
Processed 400 out of 485 windows...
Processed 450 out of 485 windows...
Total processed windows:485
Number of reads: 2994
Number of valid reads: 2950
Number of correct strand reads:0

Inside of regions...
Num mapped reads: 2950
Num mapped first of pair: 1480
Num mapped second of pair: 1470
Num singletons: 44
Time taken to analyze reads: 38
Computing descriptors...
numberOfMappedBases: 294063
referenceSize: 3137454505
numberOfSequencedBases: 294007
numberOfAs: 57962
Computing per chromosome statistics...
Computing histograms...
Overall analysis time: 38
end of bam qc
Computing report...
Writing HTML report...
#And at this point nothing else happen
```
But I do get a directory containing the report.
So I'm not really sure if the problem is due to `bianca`, `qualimap`, `singularity`, my account, myself, or just bad vibrations...

I'll try tomorrow to get more detailed output...

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Check Qualimap BamQC container that seems to have trouble on Bianca](https://trello.com/c/qgIkRgon/16-check-qualimap-bamqc-container-that-seems-to-have-trouble-on-bianca)

**Comment by MaxUlysse** [comment]
cf #420
