### ISSUE TITLE
Clean up FreeBayes and SpeedSeq filtering

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/Sarek#497]
- [x] likely vcfsamplediff should be run _after_ the speedseq filter since the latter changes the genotype
- [x] order of tumour and normal should be set at the beginning (or to be found out automatically somehow)
- [x] check SSC threshold calculation - 100 is a nice number, something between 0-1 similar to F-score would be better

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean up FreeBayes and SpeedSeq filtering](https://trello.com/c/nD4JbJgt/12-clean-up-freebayes-and-speedseq-filtering)

**Comment by szilvajuhos** [comment]
http://c1ccccc1.blogspot.se/2017/12/cancer-ngs-normal-tumour-pairs-using.html
