### ISSUE TITLE
Enhance ASCAT

### ISSUE THREAD

**Issue by malinlarsson** [SciLifeLab/Sarek#502]
Add gc correction to ASCAT. 
Also, set gamma to 1 in ASCAT run.

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhance ASCAT](https://trello.com/c/7PLoQaSk/9-enhance-ascat)

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhance ASCAT](https://trello.com/c/7PLoQaSk/9-enhance-ascat)

**Comment by MaxUlysse** [comment]
Duplicate of #407
