### ISSUE TITLE
Follow new BPs from Broad Institute due to GATK 4.0

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#503]
Some refactoring will need to be done to follow the new BPs.
Cf [Introduction to the GATK Best Practices](https://software.broadinstitute.org/gatk/best-practices/)

**Comment by apeltzer** [comment]
I'm currently modifying the NGI-ExoSeq pipeline in a separate branch [here](https://github.com/apeltzer/NGI-ExoSeq/tree/gatk4-modularize). I can summarize things then once things are running properly and let you guys know.

**Comment by MaxUlysse** [comment]
I remember, but I do need to put some ideas here ;-)

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update GATK](https://trello.com/c/LG14scXv/5-update-gatk)
