### ISSUE TITLE
Do VQSR for HaplotypeCaller calls

### ISSUE THREAD

**Issue by malinlarsson** [SciLifeLab/Sarek#513]
## Expected Behavior
Filter the calls from HaplotypeCaller with Variant Quality Score Recalibration according to GATK best practise (Tools VariantRecalibrator, ApplyRecalibration, see https://gatkforums.broadinstitute.org/gatk/discussion/39/variant-quality-score-recalibration-vqsr or a more recent version)

## Current Behavior
Variant quality score recalibration currently not included.

**Comment by szilvajuhos** [comment]
We should do it for/with GATK 4.0 only.

**Comment by malinlarsson** [comment]
Sounds like a good plan.

**Comment by MaxUlysse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Filter HaplotypeCaller variants](https://trello.com/c/tEbTVLMi/50-filter-haplotypecaller-variants)

**Comment by apeltzer** [comment]
Keep in mind, that you'd need a "bit" of data for doing VQSR properly. The recommendation was to use at least 30 WES or 1WGS sample for performing VQSR. 

I started working on a solution  (in NGI-ExoSeq) to automatically download 35 of the 1000G Exome Datasets, run HaplotypeCaller on them and use them for analysis procedures with less than the minimum required 30 WES samples.

**Comment by MaxUlysse** [comment]
Transferred to the new [nf-core/sarek](https://github.com/nf-core/sarek/) repo
