### ISSUE TITLE
No results are copied to any output directory

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/Sarek#530]
After a successful run they are staying in the work/... directory. When using /scratch it means we are loosing the results altogether. Command line was:
```nextflow run /home/szilva/sarek/default/somaticVC.nf -profile singularityPath --tools strelka --genome GRCh38 --genome_base /sw/data/uppnex/ToolBox/hg38bundle --sample Preprocessing/Recalibrated/recalibrated.tsv --containerPath /home/szilva/sarek/containers/ --noReports --verbose```

**Comment by szilvajuhos** [comment]
Looks it ts true for other tools as well.

**Comment by MaxUlysse** [comment]
OK,
I'll look into it ASAP.
Thanks for noticing that...

**Comment by MaxUlysse** [comment]
Results from `germlineVC.nf` are copied to the `VariantCalling` directory.
So the problem should be easy to find and to fix.

**Comment by MaxUlysse** [comment]
Working well on my case.
Can't seem to reproduce your problem @szilvajuhos

**Comment by szilvajuhos** [comment]
Made a test set from the DREAM challenge using only chr22 that can be found on irma at /lupus/proj/ngi2016004/private/szilva/sarek_test . There is a runTool.sh script to launch Sarek, and it was like
`/lupus/proj/ngi2016004/private/szilva/sarek_test $ ./runTool.sh freebayes 2>&1 | tee fb.log`

**Comment by MaxUlysse** [comment]
OK, so definitively this problem seems to be specific at Irma and Bianca.
I'll go CSI mode and investigate it out :mag:.
