### ISSUE TITLE
Add documentation about using other genomes

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/Sarek#540]
If we want to run Sarek Germline analysis on non-human samples, what reference files do we need?

* eg. Do we have to have dbSNP?
* Is it possible to run the pipeline without these references?
    * Can the steps that require such refs be skipped easily?
* What's the minimum that's required?

**Comment by ewels** [comment]
Maybe of interest to @viklund who is currently developing a pretty similar Nextflow pipeline to work with Canine data. Would be great if we could use Sarek with dogs for example.

**Comment by MaxUlysse** [comment]
Definitively, I'll try to look ASAP what are the minimal requirements

**Comment by MaxUlysse** [comment]
@viklund @ewels 

Currently for Germline Analysis, we're asking for the following files:
- The interval file, which can be a bed file or a simple text file cf [doc](https://github.com/SciLifeLab/Sarek/blob/master/doc/INTERVALS.md).  _which should be easy to made_.

- Reference Genome (Fasta + dict + index + bwa indexes) _which you should already have_.

- VCFs: _which is what is more interesting for you I guess_.
  - 'dbsnp' and its index for `CreateRecalibrationTable` process and `HaplotypeCaller`
  - `knownIndels` and its index (such as 1000 Genomes, Mill’s gold standard) for `RealignerTargetCreator`, `IndelRealigner` and `CreateRecalibrationTable` processes

**Comment by MaxUlysse** [comment]
> What is missing is dbsnp

We're using `dbsnp` as a `-knownSites` for `BaseRecalibrator` in the `CreateRecalibrationTable` process, so the pipeline should be able to run without it (with a few minor modifications).
and the `--dbsnp` option of `HaplotypeCaller` is [optionnal](https://software.broadinstitute.org/gatk/documentation/tooldocs/3.8-0/org_broadinstitute_gatk_tools_walkers_haplotypecaller_HaplotypeCaller.php), so same answer.

**Comment by nilesh-tawari** [comment]
@MaxUlysse @viklund @ewels, how to use Sarek with canine genome CanFam3.1?  Thank you.

**Comment by MaxUlysse** [comment]
Hi @nilesh-tawari 
I'm glad to see that you're interested into using Sarek for non-human species.
We're getting more questions about using Sarek for such an usage.
Currently what you should do is to modify the `genomes.conf` or the `igenomes.conf` file and create a new genome for that.
I have another contact who actually wants to use the same genome as you, so I already started into looking into it, and we should make some PR regarding this matter soon.
Do you have a specific file for known SNP positions?

**Comment by nilesh-tawari** [comment]
@MaxUlysse, is it possible to use Sarek with conda?

**Comment by MaxUlysse** [comment]
Haven't tested it, but it should be possible without problem, for most of it, except for ASCAT and annotation (snpEff and VEP), that are on separate containers and not currently in the environnement.yml file.
That's something that need more work into it.
I'll make a special issue for that.

**Comment by MaxUlysse** [comment]
Hi,
Sorry for not answering earlier, I'm on vacation at the moment.
We could make this bed file optional, but as it's used to speed up the pipeline, I won't advise going that way.
I think we'll go for guidelines on how to make one, or directly make one and ship it using iGenomes.

**Comment by nilesh-tawari** [comment]
@MaxUlysse , instructions to make + shipping with iGenomes sounds perfect.  We can make this after you are back.

**Comment by nilesh-tawari** [comment]
@MaxUlysse can you breifly describe guidelines on how to make bed file? I will make and test it. Thanks

**Comment by MaxUlysse** [comment]
That's actually a very good idea.
We have some small documentation about it here:
https://github.com/SciLifeLab/Sarek/blob/master/docs/INTERVALS.md
But it definitively should be updated on how to actually make such a file.

**Comment by nilesh-tawari** [comment]
@MaxUlysse Thank you, I am not able to reproduce the commands listed there, can you look into, here are the commands on the page (how is tiny.list generated?),
```
module load bioinfo-tools samtools/1.4 bwa
samtools faidx /sw/data/uppnex/ToolBox/ReferenceAssemblies/hg38make/bundle/2.8/b37/human_g1k_v37_decoy.fasta $(< tiny.list) > intervals.fasta
bwa mem /sw/data/uppnex/ToolBox/hg38bundle/Homo_sapiens_assembly38.fasta intervals.fasta > intervals.sam
grep -v '^@' intervals.sam | awk '{printf("%s:%d-%d\n", $3, $4, $4+$6-1)}' > tiny-GRCh38.list
```

**Comment by MaxUlysse** [comment]
Hi @nilesh-tawari, I'm sorry, I totally missed your comment.
Did you managed to sort this intervals problem out, or not at all?

**Comment by nilesh-tawari** [comment]
> Hi @nilesh-tawari, I'm sorry, I totally missed your comment.
> Did you managed to sort this intervals problem out, or not at all?

@MaxUlysse, I wasn't able to fix the issue. Can you suggest?

**Comment by MaxUlysse** [comment]
@nilesh-tawari 
So if I remember well, you have a bed file generated from GTF that does not work with GATK.
So you're trying to generate a new one?

**Comment by nilesh-tawari** [comment]
@MaxUlysse Yes, the bed file from GTF gives error `ERROR MESSAGE: Badly formed genome loc`. So trying to generate proper bed file for WGS

**Comment by MaxUlysse** [comment]
Which GTF did you start with?

**Comment by nilesh-tawari** [comment]
I used GTF from ensembl

**Comment by MaxUlysse** [comment]
@nilesh-tawari 
I did a small gist to get an interval file, provided you're in a folder with each chromosome
(like this bucket from AWS iGenomes: s3://ngi-igenomes/igenomes/Canis_familiaris/Ensembl/CanFam3.1/Sequence/Chromosomes/)

```bash
for i in `ls -1v`; do echo ${i%.fa}:1-$(cat $i | grep -v ">" | wc -c) ; done
```

This should give you:
```
1:1-124723432
2:1-86850487
3:1-93420528
4:1-89747909
5:1-90397171
6:1-78866698
7:1-82324108
8:1-75569257
9:1-62091984
10:1-70486972
11:1-75628916
12:1-73706383
13:1-64295956
14:1-61982791
15:1-65260816
16:1-60626727
17:1-65360544
18:1-56775593
19:1-54637308
20:1-59102957
21:1-51706267
22:1-62463933
23:1-53166055
24:1-48493759
25:1-52489416
26:1-39614102
27:1-46641322
28:1-41868481
29:1-42542659
30:1-40884498
31:1-40560854
32:1-39457120
33:1-31900019
34:1-42826505
35:1-26967083
36:1-31324512
37:1-31418041
38:1-24313113
MT:1-17006
X:1-125933628
```

Which should be a working intervals file, but not optimized.
To improve it I'll cut out the NNNN parts.

I'm hoping this can help you.
All the best,
Maxime

**Comment by MaxUlysse** [comment]
Documentation is done on [nf-core/sarek](https://github.com/nf-core/sarek) (all genomes are on AWS iGenomes)
