### ISSUE TITLE
Consider using PROSIC2

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#549]
[PROSIC](https://github.com/prosic/prosic2) is a caller for somatic variants in tumor-normal sample pairs, sequenced with any next-generation sequencing technology. It provides a novel latent variable model that integrates various levels of uncertainty, and thereby allows to properly asses the probability of having a somatic variant while controlling the false discovery rate.

**Comment by szilvajuhos** [comment]
See #666
