### ISSUE TITLE
Rewrote docker containers using bioconda environment.yml ?

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#551]
cf https://github.com/SciLifeLab/NGI-RNAseq/pull/216

**Comment by MaxUlysse** [comment]
Tried to update our most complicated container (the one with the most tools: `sarek`) using this method.
First the pros:
- I like the simplicity of the method.
- No need to tailor the installation for each tools.
But the `miniconda` base image (234 MB) is quite larger than the base `debian:8` image (53 MB).
So the resulting image is obviously larger (470 MB) than what we have (245 MB).

What do you think?

**Comment by marcelm** [comment]
You may be able to reduce the size somewhat by putting an `&& conda clean -a` after the `RUN conda install ...`

**Comment by MaxUlysse** [comment]
Good point, I'll try that ;-)

**Comment by MaxUlysse** [comment]
@apeltzer 
My concern is not the fact that it is 200+MB but more that it is almost twice the amount.
But regarding that I have other containers that are much more bigger on a higher order of magnitude, I can work with that.

**Comment by MaxUlysse** [comment]
@marcelm tried it, and it's now 387 MB so almost 100 MB down, which I can accept given the simplicity it will give us in installing all the tools.

**Comment by ewels** [comment]
For what it's worth, I've ported the MethylSeq and RNA pipelines to this method now and I'm totally in love with it 😄  Especially with the cool [`nf-core lint .`](https://github.com/nf-core/tools) command which warns you if there are newer versions of any packages available...

**Comment by MaxUlysse** [comment]
closed by #607
