### ISSUE TITLE
Simplify configuration

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#559]
On Irma they're using a `sarek` function, which is like:
```
sarek () 
{ 
    nextflow run /path/to/sarek/$1 -c /path/to/config/sarek_specific.config -profile slurm ${@:2};
}
```

and in the config file there is:
```
params.project = 'PROJECTID'
params.containerPath = '/Path/To/Containers'
params.tag = '2.0.0'
```

We had some trouble with probably some configuration priorities, but that's a separate issue (probably a Nextflow one).

But at least, we should try to explore and simplify this process.

**Comment by MaxUlysse** [comment]
ping @senthil10

**Comment by senthil10** [comment]
@MaxUlysse So this issue also covers the `genome_base` problem ?

**Comment by MaxUlysse** [comment]
Definitively.
I want to be able to launch Sarek via only
```
sarek main.nf --sample sample.tsv
```

**Comment by MaxUlysse** [comment]
Done on [nf-core/sarek](https://github.com/nf-core/sarek)
