### ISSUE TITLE
Consider Googles DeepVariant Caller

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#576]
cf https://github.com/nf-core/ExoSeq/issues/10

**Comment by szilvajuhos** [comment]
Switch to [CNNScoreVariants](https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.3.0/org_broadinstitute_hellbender_tools_walkers_vqsr_CNNScoreVariants.php) , see #666
