### ISSUE TITLE
Singularity is failing on Travis

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#589]
Singularity has been failing on Travis for like a week.
It's a problem with the installation of `squashfs-tools`.
At first it was not even finding the package and now it's just not possible to install it:
```
The following NEW packages will be installed:
  squashfs-tools
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 90.8 kB of archives.
After this operation, 276 kB of additional disk space will be used.
Err:1 http://us-central1.gce.archive.ubuntu.com/ubuntu trusty-updates/main amd64 squashfs-tools amd64 1:4.2+20130409-2ubuntu0.14.04.1
  404  Not Found [IP: 35.202.204.188 80]
E: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/main/s/squashfs-tools/squashfs-tools_4.2+20130409-2ubuntu0.14.04.1_amd64.deb  404  Not Found [IP: 35.202.204.188 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

This time it's not due to Singularity itself but to Travis, but I find that Singularity is not reliable enough for Travis.
Shall we remove it?
Shall we keep it?
Any thoughts on that matter?

**Comment by marcelm** [comment]
I think this particular problem would be fixed by adding the `apt-get update` step, as the error message suggests.

**Comment by MaxUlysse** [comment]
I'm back to the error I had at the beginning of the week:
```E: Unable to locate package squashfs-tools```
But my question was more, should we keep doing CI with Singularity, and use only Docker for CI, but still check with Singularity when we release a new version, or should we try again to fix Singularity on Travis CI before it fails again?
