### ISSUE TITLE
Error with SLURM executor on Bianca

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#630]
**Bug**
Error with SLURM executor

**Error**
```
sbatch: error: Batch job submission failed: Requested partition configuration not available now

Aug-30 15:50:57.073 [Task submitter] ERROR nextflow.processor.TaskProcessor - Error executing process > 'MarkDuplicates (SAMPLEXXX)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: error: Batch job submission failed: Requested partition configuration not available now
```

**System:**
 - Hardware: UPPMAX Bianca
 - Executor: slurm

**Nextflow:**
 - Version: 0.31.0

**Container engine:**
 - Engine: Singularity

**Container:**
 - tag: 2.0.0

**Additional context**
Bug find by Katja running WES samples on Bianca

**Comment by alneberg** [comment]
Not sure at all but guessing: Could it be requesting too much memory or cpus? Perhaps if it is the second or third try?

**Comment by MaxUlysse** [comment]
No changes between settings, and Sarek was already used to run completely some samples already.
It's WES, so it is quicker and require less memory.
I'm more thinking about an outside problem, so I'll have her try again today, and I'll see it's there again.

**Comment by alneberg** [comment]
For version 2.0.0, this is the config for uppmax-slurm and MarkDulicates:

```
  $MarkDuplicates {
    cpus = 1
    memory = {params.singleCPUMem * 8 * task.attempt}
    queue = 'core'
    time = {params.runTime * task.attempt}
  }
```
If this was attempt 2 or 3 for this specific sample, the value for mainly memory could be more than what is available on bianca, right?

**Comment by arontommi** [comment]
I got this error randomly this week as well. it was in a middle of a nf-core/RNAseq run on bianca on a star process, so my guess is that this was something temporary on the cluster side of things. have you tired resuming it ? i am currently waiting for a resume to start, will report back with results

**Comment by MaxUlysse** [comment]
@arontommi Thanks a lot. My user is trying the same thing as well.

**Comment by MaxUlysse** [comment]
I relaunched an inspected the work directory.
It's definitively a memory issue.
The jobs are being killed:
```
slurmstepd: error: Your job 5508 uses too much memory, cancelling it. It uses 13938315264 bytes, but max is 7516192768.
slurmstepd: error: *** JOB 5508 ON sensXXXXXXXX-b34 CANCELLED AT 2018-08-31T15:36:00 ***
```

**Comment by MaxUlysse** [comment]
These error is the one before the job gets relaunched and probably exceed the memory limit.

**Comment by alneberg** [comment]
Ah! The memory is adjusted with the new attempt, but the number of cpus are still the same. Increasing the number of cpus is the same thing as increasing the memory on uppmax/slurm. Not sure if asking for more memory without changing the cpu actually works. Do you?

**Comment by MaxUlysse** [comment]
I tried asking more that 110.GB and it fails.
So yeah, I don't think it work

**Comment by alneberg** [comment]
Yes, you need to add "-C fat" or "-C mem512GB" for that. But I think you even would get 7.5 GB if you request for 20G memory and 1 core?

**Comment by MaxUlysse** [comment]
It has been running for at least 10 minutes with:
```
  $MarkDuplicates {
    clusterOptions = {"-C fat -A $params.project"}
    queue = 'node'
    time = {params.runTime * task.attempt}
  }
```
So I think we got it.
Thanks @alneberg for the help.

For the future, I think we should try one thin node, then one fat node, it's definitively no use trying to request more memory than available.

@arontommi you should check the memory or the cpus requirement in your case as well I think

**Comment by alneberg** [comment]
Maybe this can be something useful as well:
https://github.com/nf-core/rnaseq/blob/44f1525d7adfa3a6afcafdcf7730eca78a1a2511/nextflow.config#L153

**Comment by MaxUlysse** [comment]
Definitively

**Comment by MaxUlysse** [comment]
Issue fixed, so I'm closing this issue.
Just mentioning the other configuration related issue here: #504 #559
