### ISSUE TITLE
Consider other tools

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#666]
EDIT with a checklist of tools

- [ ] [ExpansionHunter](https://github.com/Illumina/ExpansionHunter) for estimating repeat sizes
- [ ] [QDNAseq](https://github.com/ccagc/QDNAseq) CNVs for shallow WGS
- [ ] [CNVkit](https://github.com/etal/cnvkit) for CNVs
- [ ] [deconstructSigs](https://github.com/raerose01/deconstructSigs) for mutational signatures
- [ ] ditto [mutation-signatures](https://github.com/mskcc/mutation-signatures) 
- [ ] [SomaticSeq](https://github.com/bioinform/somaticseq) ensemble caller and machine learning
- [ ] [MSIsensor](https://github.com/ding-lab/msisensor) for replication slippage variants at microsatellite regions
- [ ] [Oncotator](https://portals.broadinstitute.org/oncotator/) for annotating human point mutations and indels
- [ ] [MutSig](https://software.broadinstitute.org/cancer/cga/mutsig) for Mutation Significance checks
- [ ] [HsMetrics](https://broadinstitute.github.io/picard/javadoc/picard/picard/analysis/directed/HsMetrics.html) better QC 
- [ ] [CNNScoreVariants](https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.3.0/org_broadinstitute_hellbender_tools_walkers_vqsr_CNNScoreVariants.php) Annotate a VCF with scores from a Convolutional Neural Network (CNN). 
- [ ] [SignatureAnalyzer](https://software.broadinstitute.org/cancer/cga/msp) yet an other mutation signature analyser from Broad
- [ ] [PROSIC2](https://github.com/prosic/prosic2) is a caller for somatic variants in tumor-normal sample pairs
- [ ] [seqCAT](https://github.com/fasterius/seqCAT) Evaluation of SNV profiles
- [ ] [varlociraptor](https://github.com/varlociraptor/varlociraptor) A Rust library for variant calling using a latent variable model
- [ ] [GATK CNN](https://software.broadinstitute.org/gatk/documentation/tooldocs/current/org_broadinstitute_hellbender_tools_walkers_vqsr_CNNScoreVariants.php) Convolutional Neural Net to filter annotated variants

**Comment by MaxUlysse** [comment]
Latest version available on bioconda is 2.0.8.
Latest version is 2.5.5, so it would good to update the recipe on bioconda to facilitate the use of this tool

**Comment by apeltzer** [comment]
You're welcome ;-) https://github.com/bioconda/bioconda-recipes/pull/11386

**Comment by apeltzer** [comment]
To be fair: That one was super easy ;-)

**Comment by MaxUlysse** [comment]
I'm impressed it was that easy.
Thanks a lot.

**Comment by szilvajuhos** [comment]
The checklist for all the others we should check:

- [ ] [ExpansionHunter](https://github.com/Illumina/ExpansionHunter) for estimating repeat sizes
- [ ] [QDNAseq](https://github.com/ccagc/QDNAseq) CNVs for shallow WGS
- [ ] [CNVkit](https://github.com/etal/cnvkit) for CNVs
- [ ] [deconstructSigs](https://github.com/raerose01/deconstructSigs) for mutational signatures
- [ ] ditto [mutation-signatures](https://github.com/mskcc/mutation-signatures) 
- [ ] [SomaticSeq](https://github.com/bioinform/somaticseq) ensemble caller and machine learning

**Comment by MaxUlysse** [comment]
Transferred to the new [nf-core/sarek](https://github.com/nf-core/sarek/) repo
