### ISSUE TITLE
BuildReferences issues / files get deleted

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/Sarek#667]
**Describe the bug**

Tried building GRCH37 references as described in your tutorial. However, running that on a different machine than your profiles enable did result in resetting the input files to zero byte files unfortunately.

**To Reproduce**

Downloaded the four files:
```

    242c0df2a698a76fc43bdd938ba57c62 - '1000G_phase1.indels.b37.vcf.gz'
    00b0e74e4a13536dd6c0728c66db43f3 - 'dbsnp_138.b37.vcf.gz'
    dd05833f18c22cc501e3e31406d140b0 - 'human_g1k_v37_decoy.fasta.gz'
    a0764a80311aee369375c5c7dda7e266 - 'Mills_and_1000G_gold_standard.indels.b37.vcf.gz'

```

Now, I ran with: 

`nextflow run Sarek/buildReferences.nf --refDir . --genome 'GRCh37' -profile binac --genome_base .`

This resulted in all files being zeroed, e.g. having file size 0 bytes afterwards. No references were created :-( 

**Expected behavior**

I expected the references to be indexed properly :-) 

**System (please complete the following information):**
 - Hardware: HPC system (binac), local workstation with combination of `singularity` and basic profile `ws.config` i created 
 - Executor: [e.g. slurm, local, awsbatch...] PBS or local 
 - OS: [e.g. CentOS Linux, macOS, Linux Mint...] CentOS 7
 - Version [e.g. 7, 10.13.6, 18.3...] latest

**Nextflow (please complete the following information):**
 - Version: [e.g. 0.31.0] 0.32.0 

**Container engine (please complete the following information):**
 - Engine: [e.g. Conda, Docker or Singularity] Singularity
 - version: [e.g. 1.0.0] 2.5.2 or 2.6.0 

**Container (please complete the following information):**
 - tag: [e.g. 1.0.0] 2.2.1

**Sarek (please complete the following information):**
 - version: [e.g. 2.1.0] 2.2.1 Skarski

Attached the `ws.config` i added in my local copy of Sarek for testing purposes:

[ws.config.txt](https://github.com/SciLifeLab/Sarek/files/2499063/ws.config.txt)

I added it as a different profile in Sarek itself to `nextflow.config`

```
  testalex {
    includeConfig 'conf/base.config'
    includeConfig 'conf/ws.config'
    includeConfig 'conf/singularity.config'
  }
```

**Comment by MaxUlysse** [comment]
cf #504 #559

**Comment by MaxUlysse** [comment]
Do you think it could be to the publishDir mode issue #669 ?

**Comment by apeltzer** [comment]
I will send you a PR with our cluster profile(s) that I now use and then I could test it properly again. Not so sure about it tbh, but could be related yes.
