### ISSUE TITLE
Handle Memory / CPU Configuration more explicitly? 

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/Sarek#668]
**Is your feature request related to a problem? Please describe.**

My experience with nf-core pipelines suggests that memory requirements are handled centrally, e.g. by defining these in a `base.config` file on a per-process level, which can then be imported by various infrastructure profiles easily. (example [here for the rnaseq pipeline](https://github.com/nf-core/rnaseq/blob/master/conf/base.config)) 

This makes it incredibly easy for users to define their own hardware-specific profiles by adding on top, e.g. 

base, <hwprofile>, (singularity|docker) - done!

I was quite unsure how to do this in Sarek properly and had to come up with an entire profile describing these resource requests, hardware specific configuration parameters etc pp.

One issue was for example in using the `buildReferences.nf` script, when the `toGiga()` method requires a memory parameter to be set, which wasn't done in our binac profile so far. There was no mentioning of that in the documentation, so I added it myself, but more newbie users might be lost with that info unfortunately. 

**Describe the solution you'd like**

Being able to define just the hardware specific requirements (e.g., cluster scheduler, max memory, max cpus) and then using the pipeline as is :-) 

**Describe alternatives you've considered**

Adding my own profiles from scratch, which is quite a lot of work and would be required by anyone else trying to use the pipeline too :-)

**Comment by MaxUlysse** [comment]
cf #504 #559

**Comment by MaxUlysse** [comment]
Done on [nf-core/sarek](https://github.com/nf-core/sarek)
