### ISSUE TITLE
Target Coverage in BAMQC

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/Sarek#670]
**Is your feature request related to a problem? Please describe.**

The target coverage is computed in BAMQC based on the entire genome. For exome data (even with specified BED file and therefore regions, Sarek doesn't specify the coverage on covered sites but instead the overall coverage on the entire genome. 

**Describe the solution you'd like**

Use the `--gff` switch in QualiMap2 to run with the specified BED file. That provides more accurate coverage on target capture coverage.

**Comment by szilvajuhos** [comment]
Cool, other groups were also requesting something similar, I already made some prototype, we can also add the QualiMap2 part. Will work on that.

**Comment by apeltzer** [comment]
Just make sure to use a more updated QualiMap2 version. The possibility to use BED-3 instead of BED-6 format, was just introduced fairly recently (upon my request... https://bitbucket.org/kokonech/qualimap/commits/all ). I don#t know which version of QualiMap2 is shipped with the current Sarek container(s), so we should make sure that this works :-)

**Comment by MaxUlysse** [comment]
Transferred to the new [nf-core/sarek](https://github.com/nf-core/sarek/) repo
