### ISSUE TITLE
Check BED compatibility

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/Sarek#687]
**Is your feature request related to a problem? Please describe.**

Not really ;-) But this happens quite often when people use a target capture method. 

**Describe the solution you'd like**

A small extra process that checks BED files for consistency with the utilized reference genome. Either check only and issue a warning or also offer to remove the `chr`prefix for example ;-)

**Comment by apeltzer** [comment]
Can do that if you guys don't mind :-)

**Comment by MaxUlysse** [comment]
That would be amazing \o/

**Comment by MaxUlysse** [comment]
Transferred to the new [nf-core/sarek](https://github.com/nf-core/sarek/) repo
