### ISSUE TITLE
Sex determination Option

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/Sarek#688]
**Is your feature request related to a problem? Please describe.**

If you don#t know the sex of an individual, one could run simple scripts to perform sex determination. This is commonly done in population genetics and there are quite a bunch of scripts to perform that automatically, more or less checking chrX/chrY ratios with thresholds.

**Describe the solution you'd like**

Having an optional step may be to run sex determination, as we do have cases where we don't have the information....

**Comment by MaxUlysse** [comment]
Definitively a good idea.
We tough about it at some point, it could even be a QC step to verify the sex that was given in the TSV file

**Comment by MaxUlysse** [comment]
Transferred to the new [nf-core/sarek](https://github.com/nf-core/sarek/) repo
