### ISSUE TITLE
Multi-Sample Output Organization

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/Sarek#691]
**Is your feature request related to a problem? Please describe.**

Currently, output is organized in a way that every VCF file lands in a single folder.

**Describe the solution you'd like**

 It would be nice to have the possibility, if users can specify a single TSV containing multiple patients and the generated VCFs etc are stored nicely in 

**Describe alternatives you've considered**

Creating n TSV files for each patient individually, which is quite cumbersome... 

We discussed this together with @ggabernet @MaxUlysse on Gitter :-)

**Comment by ggabernet** [comment]
Currently it is possible to add as an input a TSV containing multiple patients, but I realized that somatic variant calling then calls all possibilities of tumor-normal pairs, even between different patients, so this would need to be fixed too.

**Comment by MaxUlysse** [comment]
I can see why this is happening, thanks for telling me about it

**Comment by ggabernet** [comment]
sure, I'm very happy to use your pipeline!

**Comment by MaxUlysse** [comment]
I'm glad that you're using it, with more user like you, Sarek can only improve its quality ;-)

**Comment by jongtaek-kim** [comment]
> somatic variant calling then calls all possibilities of tumor-normal pairs, even between different 
patients,
> 

Has this been addressed yet? This wastes the time and computing resources exponentially as the number of patients increase.
I am resorting to running each patient T/N separately.

**Comment by MaxUlysse** [comment]
Hi,
I'm sorry, I didn't manage to find time to implement that yet.
But it's definitively something that I plan for our next release.

**Comment by MaxUlysse** [comment]
The bug encountered by @ggabernet will be fixed by #728.
Concerning the organization of files, is this just the vcfs that are posing an issue for you?
or would you want separate directories for the bams as well?

**Comment by ggabernet** [comment]
I would say the vcfs would be enough. Thanks for checking this!

**Comment by MaxUlysse** [comment]
Thanks for your input.
@jongtaek-kim what is your use case?

**Comment by jongtaek-kim** [comment]
@MaxUlysse 
I am running the pipeline on exome T/N samples to detect somatic snvs and indels in my academic health center's HPC.  Thanks for the pipeline repo.

**Comment by MaxUlysse** [comment]
@jongtaek-kim I can see why you're interested in this issue.
I does indeed makes a lots of sense to have that for exome.

Are VCFs organized in patient specific folder enough for you ?
Are you interested in the same thing for BAMs as well ?

**Comment by jongtaek-kim** [comment]
> Are VCFs organized in patient specific folder enough for you ?
Are you interested in the same thing for BAMs as well ?

After doing some thinking, I think both are good ideas to implement.

**Comment by MaxUlysse** [comment]
OK, so the VCFs are to be separated in PR #728 
I'll work on the Bams later on

**Comment by jongtaek-kim** [comment]
@MaxUlysse Thank you so much.

Also, appreciate getting the targetBED fixed. [https://github.com/SciLifeLab/Sarek/pull/728/commits/eb3dfb1649e4f374b84a6c88a905435c97b0b7fe](url) 
Did little test run on dev branch and can attest --targetBED paramter worked.
This goes well with my exome sequencing where I have to provide a bed file. 
Will run the whole thing with #728 merged dev and will see how it goes.
