### ISSUE TITLE
Add ControlFREEC

### ISSUE THREAD

**Issue by szilvajuhos** [SciLifeLab/Sarek#695]
ControlFREEC http://boevalab.com/FREEC/ is giving pretty valuable information for both WGS and WES  samples. First we should add the default WGS version. @MaxUlysse already have a branch: https://github.com/MaxUlysse/Sarek/tree/controlfreec and looks promising.

**Comment by MaxUlysse** [comment]
I'm starting tests on the ICGC data

**Comment by MaxUlysse** [comment]
Done on [nf-core/sarek](https://github.com/nf-core/sarek)
