### ISSUE TITLE
FastQC hangs forever on Travis CI

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#701]
**Describe the bug**
- FastQC hangs forever on Travis CI (or at least more than 10 min)

**To Reproduce**
- Relaunch any Travis CI jobs that is currently failing

**Expected behavior**
- FastQC should finish in just a couple of minutes (or even less)

**System (please complete the following information):**
 - Hardware: TravisCI
 - Executor: local
 - OS: TravisCI
 - Version TravisCI

**Nextflow (please complete the following information):**
 - Version: 0.32.0

**Container engine (please complete the following information):**
 - Engine: Docker
 - version: TravisCI

**Container (please complete the following information):**
 - tag: latest

**Sarek (please complete the following information):**
 - version: dev

**Additional context**
```
[30/4e318f] Submitted process > RunFastQC (1234-1234N_M1)
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by apeltzer** [comment]
Here you go: https://github.com/bioconda/bioconda-recipes/pull/12616
