### ISSUE TITLE
Make Sarek work with Conda

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#707]
As discussed in #540, it would be interesting to have Sarek fully work with Conda.

> @MaxUlysse, is it possible to use Sarek with conda?

> Haven't tested it, but it should be possible without problem, for most of it, except for ASCAT and annotation (snpEff and VEP), that are on separate containers and not currently in the environnement.yml file...

**Comment by nilesh-tawari** [comment]
@MaxUlysse, I tried to use it with conda. 

I created a config file for cluster and conda env using the yml file
```
process.executor = 'sge'
process {
  beforeScript = { 'module load anaconda; set +u; source activate sarek-2.2.1; set -u;' }
  errorStrategy = { task.attempt < 2 ? 'retry' : 'finish' }
  executor='sge'
  penv='smp'
  clusterOptions = { "-l mem_free=" + task.memory.toString().replaceAll(/[\sB]/,'') }
}
```
And run Sarek using command,
```
 nextflow run SciLifeLab/Sarek/main.nf --sample sample_sheet.txt --genome_base reference_genome_CanFam3.1 --genome CanFam3.1
```
I get error due to Singularity image,
```
FATAL:   failed to retrieved path for /sarek-latest.simg: lstat /sarek-latest.simg: no such file or directory
ERROR  : Child exit with status 255
```
Thanks

**Comment by MaxUlysse** [comment]
If you don't specify any profile, the default would be standard which is using Singularity.
I think this is the issue here.

I'm sorry, I'm in a meeting at the moment, I'm afraid I can't try much right now, but if you can, I think it would be easier to make a specific profile for this usage.

**Comment by nilesh-tawari** [comment]
@MaxUlysse Thanks for the hint, after creating specific profile, I am able to run Sarek with conda.
