### ISSUE TITLE
markduplicates will fail when no lane information is given in  sample.tsv

### ISSUE THREAD

**Issue by nicweb** [SciLifeLab/Sarek#714]
When there is no lane information given in the sample.tsv markduplicates will fail with
  
htsjdk.samtools.SAMFormatException: Error parsing SAM header. Problem
parsing @RG key:value pair.

as readgroup ID is empty.

Would be nice to check TSV before  execution or autoset empty lane with sampleID or similar to avoid downstream execution halt, or update documentation that field should not be empty.

Not related but could be maybe achieved together with #626

**Comment by MaxUlysse** [comment]
That's definitively something that needs to be done.

And it would go perfectly with #626 as you proposed.

I'll work on that ASAP

**Comment by MaxUlysse** [comment]
Transferred to the new [nf-core/sarek](https://github.com/nf-core/sarek/) repo
