### ISSUE TITLE
Look into using spark for gatk

### ISSUE THREAD

**Issue by alneberg** [SciLifeLab/Sarek#730]
It seems that gatk now only supports parallelism in their tools through spark (see https://github.com/broadinstitute/gatk/issues/2345). I have no idea how spark works, but it might be worth looking into? `CreateRecalibrationTable` and `RecalibrateBam` and maybe other processes currently take a really long time. Maybe this can be improved?

**Comment by apeltzer** [comment]
Might simply work like this:
https://software.broadinstitute.org/gatk/documentation/article?id=11245

Copying the text from there over here:

You don't need a Spark cluster to run Spark-enabled GATK tools!

If you're working on a "normal" machine (even just a laptop) with multiple CPU cores, the GATK engine can still use Spark to create a virtual standalone cluster in place, and set it to take advantage of however many cores are available on the machine -- or however many you choose to allocate. See the example parameters below and the local-Spark tutorial for more information on how to control this. And if your machine only has a single core, these tools can always be run in single-core mode -- it'll just take longer for them to finish.

To be clear, even the Spark-only tools can be run on regular machines, though in practice a few of them may be prohibitively slow (SV tools and PathSeq). See the Tool Docs for tool-specific recommendations.

If you do have access to a Spark cluster, the Spark-enabled tools are going to be extra happy but you may need to provide some additional parameters to use them effectively. See the cluster-Spark tutorial for more information.
Example command-line parameters

Here are some example arguments you would give to a Spark-enabled GATK tool:
```
    --spark-master local[*] -> "Run on the local machine using all cores"
    --spark-master local[2] -> "Run on the local machine using two cores" 
```

**Comment by apeltzer** [comment]
Should be possible to run e.g. picard markduplicates like this, same for some other stuff such as BaseRecalibrator and HaplotypeCaller.

**Comment by apeltzer** [comment]
https://gatkforums.broadinstitute.org/gatk/discussion/23441/markduplicatespark-is-slower-than-normal-markduplicates

We should really look into this!

**Comment by apeltzer** [comment]
Apparently it benefits when not sorting reads prior MarkDuplicates and takes direct BWA Mem BAM output. So we should really try it :-)

**Comment by apeltzer** [comment]
We should move this over to nf-core/sarek ;)
