### ISSUE TITLE
Error with annotate.nf

### ISSUE THREAD

**Issue by Anuragksingh** [SciLifeLab/Sarek#731]
I'm trying to run annotate.nf on my vcf files (called using strelka). With both snpeff and vep I am repeatedly facing issues. Any help or suggestion will be very grateful.

**Error for vep:**
  .command.sh: line 2: /opt/vep/src/ensembl-vep/vep: No such file or directory

**Command:** nextflow run /workspace/pipeline/sarek/Sarek/annotate.nf --annotateTools Strelka --genome_base /workspace/pipeline/sarek/Sarek/References/GRCh38/ --genome GRCh38 --tools vep --tag latest -profile singularity

**Error for snpeff:**
.command.sh: line 2: SNPEFF_HOME: unbound variable

**Command:** nextflow run /workspace/pipeline/sarek/Sarek/annotate.nf --annotateTools Strelka --genome_base /workspace/pipeline/sarek/Sarek/References/GRCh38/ --genome GRCh38 --tools snpEff --tag latest -profile singularity

 **Full error message for snpeff** 
Sarek - Workflow For Somatic And Germline Variations ~ 2.2.1 - 587f366d31
Command Line: nextflow run /workspace/pipeline/sarek/Sarek/annotate.nf --annotateTools Strelka --genome_base /workspace/pipeline/sarek/Sarek/References/GRCh38/ --genome GRCh38 --tools snpEff --tag latest -profile singularity
Profile     : singularity
Project Dir : /workspace/pipeline/sarek/Sarek
Launch Dir  : /home/anurag/sarek_processing
Work Dir    : /home/anurag/sarek_processing/work
Out Dir     : /home/anurag/sarek_processing
Genome      : GRCh38
Genome_base : /workspace/pipeline/sarek/Sarek/References/GRCh38/
Tools       : snpeff
Annotate on : strelka
Containers
  Repository   : docker://maxulysse
  Tag          : latest
Reference files used:
  snpeffDb    :
	GRCh38.86
[warm up] executor > local
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /home/anurag/sarek_processing/work/singularity
Pulling Singularity image docker://maxulysse/sarek:latest [cache /home/anurag/sarek_processing/work/singularity/maxulysse-sarek-latest.img]
[6a/85b18d] Submitted process > RunSnpeff (strelka - Strelka_MDB_02_91_vs_MDB_05_118_somatic_indels.vcf.gz)
[6d/6f7fc9] Submitted process > RunSnpeff (strelka - Strelka_MDB_02_91_vs_MDB_05_118_somatic_snvs.vcf.gz)
[7a/55e80e] Submitted process > GetVersionSnpeff
ERROR ~ Error executing process > 'RunSnpeff (strelka - Strelka_MDB_02_91_vs_MDB_05_118_somatic_indels.vcf.gz)'

Caused by:
  Process `RunSnpeff (strelka - Strelka_MDB_02_91_vs_MDB_05_118_somatic_indels.vcf.gz)` terminated with an error exit status (1)

Command executed:

  java -Xmx7g   -jar $SNPEFF_HOME/snpEff.jar   GRCh38.86   -csvStats Strelka_MDB_02_91_vs_MDB_05_118_somatic_indels_snpEff.csv   -nodownload   -canon   -v   Strelka_MDB_02_91_vs_MDB_05_118_somatic_indels.vcf.gz   > Strelka_MDB_02_91_vs_MDB_05_118_somatic_indels_snpEff.ann.vcf
  
  mv snpEff_summary.html Strelka_MDB_02_91_vs_MDB_05_118_somatic_indels_snpEff.summary.html

Command exit status:
  1

Command output:
  (empty)

Command error:
  .command.sh: line 2: SNPEFF_HOME: unbound variable

Work dir:
  /home/anurag/sarek_processing/work/6a/85b18d86eff1348fd19fd2ff181130

N E X T F L O W  ~  version 18.10.1 5003

Thanks

**Comment by MaxUlysse** [comment]
Hi,
I'm guessing you're using the containers tagged `lastest`, forcing the use of a previous version like `2.2.1` or even `2.2.2` should definitively fix that.
Can you try the same command with `--tag 2.2.1`, or `--tag 2.2.2`?
What is your use case, and where are you running Sarek?

**Comment by Anuragksingh** [comment]
Hello,
Thanks for the prompt help. It's working perfectly fine with the --tag 2.2.1. We have some exome sequencing data and we are trying to call variants from them. We are using it on our computing cluster.
Thanks.

**Comment by MaxUlysse** [comment]
Don't hesitate if you have any more issue ;-)
