### ISSUE TITLE
Panel of Normals with Mutect2

### ISSUE THREAD

**Issue by Anuragksingh** [SciLifeLab/Sarek#739]
Hello,
Just a query if Panel of Normals with Mutect2  is supported here. If not any plans to implement it here?

Thanks

EDIT: Moved part of this issue to #763

**Comment by MaxUlysse** [comment]
Hi,
We're currently still working on this PoN with MuTect2, so it will be supported.

Regarding ASCAT, I'll check, but I'm not sure we're doing anything for exome with ASCAT yet.
I'll make another issue for that.

**Comment by Anuragksingh** [comment]
Thanks for the information. Looking forward for these improvements.

**Comment by jongtaek-kim** [comment]
@MaxUlysse I already have a panel of normal made and germline resource (af-only-gnomad) downloaded. It would be a plus for MuTect2 users to be able to run it with PON and germline resource easily within the Sarek.

**Comment by MaxUlysse** [comment]
@jongtaek-kim we are currently working on it (actually @szilvajuhos is doing most of the job regarding PONs)
I'm hoping we should get that soonish

**Comment by szilvajuhos** [comment]
Hej, to run ASCAT on exome you will need a separate file of SNPs that is covering the targeted

**Comment by szilvajuhos** [comment]
Looks most of the Mutect2 calling process and filtering works OK. I will launch a full-blown test tomorrow, will take some time to complete checks with and without PON. Once ready, will make a PR, hopefully next week.

**Comment by szilvajuhos** [comment]
OK, the trick is that PONs and WES are not happy together. I have to convert GetPileupSummaries still to a scatter-gather and we have to live with WGS-only Mutect2 for a while.
The problem is that MergeMutectStats normalises for the whole genome in the moment.

**Comment by MaxUlysse** [comment]
Which GATK4 are you using?

**Comment by szilvajuhos** [comment]
/opt/conda/envs/sarek-2.3/share/gatk4-4.1.1.0-0/gatk-package-4.1.1.0-local.jar that is in the sarek-conda.simg downloaded recently (last week or so)

**Comment by MaxUlysse** [comment]
it seems like there is now a 4.1.2.0-0 version, do you want to try that?

**Comment by szilvajuhos** [comment]
There are some Mutect2 improvements in 4.1.2x, but right now those are not needed: https://github.com/broadinstitute/gatk/releases/tag/4.1.2.0 . For the scatter-gather implementation 4.1x is enough right now.

**Comment by szilvajuhos** [comment]
More or less ready for initial PR, writing documentation and submitting.
