### ISSUE TITLE
Specifying interval for targeted sequencing

### ISSUE THREAD

**Issue by asura117** [SciLifeLab/Sarek#745]
Hi,
I am aligning some sequencing data using the SAREK main.nf. How can I specify a intervals.bed file specific for my targeted gene panel instead of the default wgs_calling_regions_CAW.list in the SAREK germlineVC.nf pipeline shell command.
Thanks

**Comment by MaxUlysse** [comment]
Hi @asura117 `--intervals` should do the trick to change this default list, but it's mainly used to chop up the genome for speeding up variant calling.
You might want to use `--targetBED` instead

**Comment by asura117** [comment]
Thanks for the quick response, will try --targetBED.
