### ISSUE TITLE
ERROR ~ For input string: "status"

### ISSUE THREAD

**Issue by asura117** [SciLifeLab/Sarek#748]
Hi,
I am using the --sample sample.tsv option for the main.nf option. 
nextflow run SciLifeLab/Sarek/main.nf
--sample path/sample.tsv
--genome_base path/GATK_b37_reference/b37
 --genome GRCh37 --intervals /path/xyz.bed

However I am getting the following error message
N E X T F L O W  ~  version 19.01.0
Launching `SciLifeLab/Sarek` [deadly_dalembert] - revision: a4ed8f34dc [master]
WARN: There's no process matching config selector: ConcatVCF
WARN: Access to undefined parameter `sampleDir` -- Initialise it to a default value eg. `params.sampleDir = some_value`
ERROR ~ For input string: "status"

The tsv file is in accordance with 
subject gender status sample lane fastq1 fastq2
SUBJECT_ID  XX    0    SAMPLEID    1    /samples/normal_1.fastq.gz    /samples/normal_2.fastq.gz

but with gender coloumn empty.

subject gender  status  sample  lane    fastq1  fastq2
79880           0       79880   1       /fullpath/181205_D00380_0158_AHLFWYBCX2/Project_TGL_Tray01A/Sample_79880/79880_TAAGGCGA-TAGATCGC_L001_R1_001.fastq.gz     /fullpath/181205_D00380_0158_AHLFWYBCX2/Project_TGL_Tray01A/Sample_79880/79880_TAAGGCGA-TAGATCGC_L001_R2_001.fastq.gz

many thanks,
J

**Comment by KochTobi** [comment]
### Hi there,
Could you check
* [ ] if it works when you write something in the gender column
* [ ] whether you separated the columns by tabs or by spaces
* [ ] your `TSV` file only includes the relevant data and not the header line

Those are things that I usually miss :)

**Comment by KochTobi** [comment]
Did any of this resolve the issue?

**Comment by asura117** [comment]
resolved. removed header from tsv.

**Comment by MaxUlysse** [comment]
Thanks @KochTobi for the help
