### ISSUE TITLE
Error with RunVcftools on a Manta VCF

### ISSUE THREAD

**Issue by Anuragksingh** [SciLifeLab/Sarek#750]
Hello,
I was trying to run vep to annotate manta. I am stuck with the below appended error. 

N E X T F L O W  ~  version 18.10.1 5003
Sarek - Workflow For Somatic And Germline Variations ~ 2.3 - ef015b173c
Command Line: nextflow run /home/anurag/tools/sarek_2.3_fix1/Sarek-master/annotate.nf --genome GRCh38 --genome_base /home/anurag/tools/sarek_2.3_fix1/Sarek-master/References/GRCh38/ --tag latest -profile singularity --tools vep --annotateTools manta
Profile     : singularity
Project Dir : /home/anurag/tools/sarek_2.3_fix1/Sarek-master
Launch Dir  : /home/anurag/test
Work Dir    : /home/anurag/test/work
Out Dir     : /home/anurag/test
Genome      : GRCh38
Genome_base : /home/anurag/tools/sarek_2.3_fix1/Sarek-master/References/GRCh38/
Tools       : vep
Annotate on : manta
Containers
  Repository   : docker://maxulysse
  ContainerPath: null
  Tag          : latest
Reference files used:
  snpEff DB    :
	GRCh38.86
  VEP Cache    :
	95
Completed at: Thu Mar 07 21:11:49 IST 2019
Duration    : 2.2s
Success     : false
Exit status : 1
Error report: Error executing process > 'RunVcftools (E23 - manta - Manta_MDB_RI_E23.candidateSV.vcf.gz)'

Caused by:
  Process `RunVcftools (E23 - manta - Manta_MDB_RI_E23.candidateSV.vcf.gz)` terminated with an error exit status (1)

Command executed:

  vcftools     --gzvcf Manta_MDB_RI_E23.candidateSV.vcf.gz     --relatedness2     --out Manta_MDB_RI_E23
  
  vcftools     --gzvcf Manta_MDB_RI_E23.candidateSV.vcf.gz     --TsTv-by-count     --out Manta_MDB_RI_E23
  
  vcftools     --gzvcf Manta_MDB_RI_E23.candidateSV.vcf.gz     --TsTv-by-qual     --out Manta_MDB_RI_E23
  
  vcftools     --gzvcf Manta_MDB_RI_E23.candidateSV.vcf.gz     --FILTER-summary     --out Manta_MDB_RI_E23

Command exit status:
  1

Command output:
  (empty)

Command error:
  
  VCFtools - 0.1.16
  (C) Adam Auton and Anthony Marcketta 2009
  
  Parameters as interpreted:
  	--gzvcf Manta_MDB_RI_E23.candidateSV.vcf.gz
  	--out Manta_MDB_RI_E23
  	--relatedness2
  
  Using zlib version: 1.2.11
  After filtering, kept 0 out of 0 Individuals
  Error: Require Genotypes in VCF file in order to output Individual Relatedness.

Work dir:
  /home/anurag/test/work/ae/9f4c57fa4d870080b64231e9a4bd68

Kindly have a look at this.
Thanks

**Comment by MaxUlysse** [comment]
Hi,
It's actually an issue with VCF tools.
I think I'll disable that QC tool for Manta VCFs, or try to catch this output error.
Try relaunching with `--noReports`

**Comment by Anuragksingh** [comment]
It works perfectly fine with --noReports.

Thanks
