### ISSUE TITLE
Reference for ASCAT required even when not calling with ASCAT

### ISSUE THREAD

**Issue by ggabernet** [SciLifeLab/Sarek#754]
Hi Maxime, thank you for incorporating ASCAT to the toolset of Sarek, it will be very useful for CNV analysis! 
However, I have the issue now that when executing the somatic VC procedure, even when ascat is not used, it requires the ascat reference:

```
Launching `scilifelab/Sarek` [amazing_goldberg] - revision: a4ed8f34dc [2.3.FIX1]
WARN: There's no process matching config selector: MapReads
Missing references: acLociGC /sfs/4/qbic/references/human/1000G_phase3_20130502_SNP_maf0.3.loci.gc
ERROR ~ Missing Reference file(s), see --help for more information
```

The command executed was:
```
nextflow run scilifelab/Sarek/somaticVC.nf -r 2.3.FIX1 --sample Preprocessing/Recalibrated/recalibrated.tsv -profile cfc --genome GRCh37 --tools strelka -resume
```

Would it be possible to only check for this reference file if the tool ASCAT is used for calling?

**Comment by MaxUlysse** [comment]
That's a very good point.
I'll look into it.

**Comment by ggabernet** [comment]
thank you!
