### ISSUE TITLE
Provide ASCAT GC File via iGenomes

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/Sarek#755]
**Is your feature request related to a problem? Please describe.**

We found the https://github.com/SciLifeLab/Sarek/blob/master/docs/ASCAT.md GC correction part to be missing on iGenomes at the moment and we'd have to manually create it.

**Describe the solution you'd like**

Maybe add it to iGenomes for GRCH37 and GRCH38 ? 

**Describe alternatives you've considered**

Creating it on our own ;-)

**Comment by MaxUlysse** [comment]
Ohhh, sorry about that, I have the files on UPPMAX webexport, and on an S3 bucket, but haven't manage to find time to synchronize it.
I'll ask Phil to help me out with it.
In the mean time, you can download them here: https://export.uppmax.uu.se/sllstore2017079/Sarek/

**Comment by apeltzer** [comment]
Ok nice - I downloaded them and will put them in our iGenomes folder. Might just make sense to have them in the iGenomes resource too for the future 👍

**Comment by MaxUlysse** [comment]
Done
