### ISSUE TITLE
Questions about Strelka -BP

### ISSUE THREAD

**Issue by MaxUlysse** [SciLifeLab/Sarek#764]
From @Anuragksingh
> Hello,
> I had some doubts over strelka -BP [...]. It would be really helpful if you can provide some insights about that.
> How is strelka different from strelka -BP (does strelka -BP includes the sv from manta as input automatically and also does the --exome flag is enabled on strelka -BP)?
> [...]
> Any suggestions on above aspects would be really helpful.
> Thanks

**Comment by MaxUlysse** [comment]
Hi @Anuragksingh 
Regarding Strelka BP (that you can access with the `--StrelkaBP` option on the command line in Sarek)
Currently it does include the candidateSmallIndels from Manta (hence the BP), but only if you run Manta at the same time.
```
nextflow run somaticVC.nf --tools Strelka,Manta --StrelkaBP
```
I'll modify that so that it can fetch it, if you already run Manta previously, so you don't have to re-run it again.
And the `--exome` flag is enabled on all `Strelka` and `Manta` processes if you provide a target BED file with `--targetBED` on the command line.
I'm hoping this answered your question

**Comment by Anuragksingh** [comment]
Thanks a lot for the info.
