### ISSUE TITLE
Parallelisation of CreateRecalibrationTable

### ISSUE THREAD

**Issue by kokyriakidis** [SciLifeLab/Sarek#769]
Hello,
Since I saw this step uses only on core on my 20 core system, I searched on GATK forum and found this:
```
https://gatkforums.broadinstitute.org/gatk/discussion/23453/gatk4-baserecalibrator-multithreading-not-spark
```
Do you think it could be something you could implement?

**Comment by MaxUlysse** [comment]
That does seems interesting.
I'll look into it.

**Comment by MaxUlysse** [comment]
You can try https://github.com/MaxUlysse/Sarek/tree/ParallelizeMore
That should be a good start in improving all that

**Comment by MaxUlysse** [comment]
Done on [nf-core/sarek](https://github.com/nf-core/sarek)
