### ISSUE TITLE
Should we include CADD annotations?

### ISSUE THREAD

**Issue by kokyriakidis** [SciLifeLab/Sarek#772]
Why we download whole_genome_SNVs without annotations?

**Comment by MaxUlysse** [comment]
Based on the CADD plugin doc, I though that you did not need the annotation to make it work.
We're actually still working on this particular plugins, do you think the annotations should be included as well?

**Comment by kokyriakidis** [comment]
As a Pharmacist and a genome researcher, Annotation is extremely helpful in understanding how this genome disturbance affect other systems and how. Of course it works without annotation, but you miss the major functionality of this tool eg the relevant and truth information about this specific variation
