### ISSUE TITLE
Missing hints for capital letters required

### ISSUE THREAD

**Issue by silviamorins** [SciLifeLab/Sarek#782]
Hi,
I was running the main.nf script as follows:

```nextflow run scilifelab/sarek/main.nf -r dev```

and it was repeatedly giving me as error:

`$ ./runMain.sh 
N E X T F L O W  ~  version 19.01.0
Project `scilifelab/Sarek` contains uncommitted changes -- Cannot switch to revision: dev`

After different attempts, it turned out that the solution was to write the name with the correct upper case letters: `SciLifeLab/Sarek`

However, the error it threw was not very helpful - I would have rather wished to receive a complaint because of no name matching?

**System:**
 - Hardware: Cluster
 - Executor: slurm
 - OS: Linux Ubuntu
 - Version 18.04

**Nextflow:**
 - Version: 19.01.0

**Container engine:**
 - Engine: Singularity
 - version: 3.0.3

**Sarek:**
 - version: dev

**Comment by MaxUlysse** [comment]
I'm afraid this is more an NF issue, but I'll make a simple reproducible error, and make an issue on NF.
Thanks a lot for reporting this error.
I'm glad that we managed to find an easy fix for it.
