### ISSUE TITLE
Target Bed for HaplotypeCaller

### ISSUE THREAD

**Issue by kokyriakidis** [SciLifeLab/Sarek#786]
I want to run HaplotypeCaller on specific target regions. I have downloaded the target region's bed file from Illumina but when I run germlineVC.nf with --targetBED option, HaplotypeCaller does calling on all regions on wgs interval file described in the genomes config file.

Shouldn't HaplotypeCaller run on only these target regions?

**Comment by MaxUlysse** [comment]
From what I remember, it was more efficient to do the calls on the whole genome, and then filter out what was in the target regions.
I'll look more into it and came with a better explanation.

**Comment by kokyriakidis** [comment]
From what I MAYBE have read from Geraldine, calling on whole genome instead of target regions, increase the noise and yield worse results. I will look into it again

**Comment by apeltzer** [comment]
The Best Practices initially stated that yes. However, this might not be correct anymore - last time I saw this was with UnifiedGenotyper, that was using a totally different model than the newer HaplotypeCaller (+ CNN Filter is even more different)

**Comment by szilvajuhos** [comment]
We are not calling through the all genome, we are leaving out centromeres and telomeres, also some nasty repeats and low complexity regions. 
The repeats/wgs_calling_regions.bed should refer to our calling targets.

**Comment by apeltzer** [comment]
That makes sense 👍

**Comment by kokyriakidis** [comment]
@apeltzer Ok, maybe there is no problem in your approach BUT wouldn't it be A LOT QUICKER to do calling on the TargetBED positions specified?

**Comment by szilvajuhos** [comment]
No, because for WES you have 200K+ targets: that means 4-5 times 200+ forks, directories, files, symlinks, etc. Just kills the cluster/node/filesystem. 
At least killed ours ;)

**Comment by kokyriakidis** [comment]
@szilvajuhos 
Hahaha I haven't thought about that! Thank you very much for having tested all that!
So, the only thing left to increase the speed of the analysis is to use the Spark version of HaplotypeCaller in order to use all threads of the CPU.

**Comment by szilvajuhos** [comment]
Indeed, likely that would be a better approach than the current architecture, but never played with that.

**Comment by kokyriakidis** [comment]
GATK states that it is super easy to use the Spark version and can run on every system without much work. Have a look into it, it is something really worth the trouble.

**Comment by MaxUlysse** [comment]
That is definitively something that we want to explore.
@alneberg mentionned it in #730

**Comment by apeltzer** [comment]
I just out of interest checked it out: Might require to check whether the bundled GATK version is indeed a SPARK one, but otherwise seems to just require the addition of a single CLI parameter. 

`--spark-master local[2]` (to use 2 cores on your local machine, given that SPARK is installed - 

https://gatkforums.broadinstitute.org/gatk/discussion/11245/spark

If I read this accordingly, it might even work with the conda GATK 4.+ version out of the box just adding this parameter (to all SPARK compatible tools): 


```
All the necessary software for using Spark, whether it's on a local machine or a Spark cluster, is bundled within the GATK itself. Just make sure to invoke GATK using the gatk wrapper script rather than calling the jar directly, because the wrapper will select the appropriate jar file (there are two!) and will set some parameters for you.
```

I might actually try this out and report back 👍

**Comment by kokyriakidis** [comment]
@apeltzer Did you try out spark?
