### ISSUE TITLE
Annotation with both SnpEff and VEP

### ISSUE THREAD

**Issue by kokyriakidis** [SciLifeLab/Sarek#792]
What it the difference between the "merge" option and the "SnpEff,VEP"? Will I see different results?

**Comment by MaxUlysse** [comment]
I'm guessing the documentation wasn't clear enough.
Sorry about that.

If you specify `snpeff,vep`, you'll get your VCFs annotated by `snpEff`, and by `VEP`, meaning one different annotation for each annotator.
If you specify `merge`, you'll get your VCFs first annotated by `snpEff`, then the resulting VCFs will be annotated by `VEP`, meaning final VCFs annotated by both annotators.

https://github.com/SciLifeLab/Sarek/blob/master/docs/ANNOTATION.md
