### ISSUE TITLE
Coverage 0.0X on whole exome sequencing data

### ISSUE THREAD

**Issue by silviamorins** [SciLifeLab/Sarek#794]
Hi,
I executed Sarek on whole exome sequencing data and in the MultiQC report, under General statistics, column "Coverage", I get values of 0.0X. I already chatted with @apeltzer about it: it is probably because, as said, I have sequences coming only from exons, and am missing all the rest of the base pairs in the genome.

I would expect the coverage calculation to take into account the fact that one might nor be dealing with whole-genome sequencing data.

**System:**
 - Hardware: cluster
 - Executor: slurm
 - OS: Linux Ubuntu
 - Version 18.04.02

**Nextflow:**
 - Version: 19.01.0.5050

**Container engine:**
 - Engine: Singularity
 - version: 3.0.3

**Sarek:**
 - version: dev

**Comment by apeltzer** [comment]
I'll do this :-)

**Comment by silviamorins** [comment]
Thanks @apeltzer :-)

**Comment by apeltzer** [comment]
Done :-)
