### ISSUE TITLE
Strange VCFTools graphs in MultiQC report

### ISSUE THREAD

**Issue by silviamorins** [SciLifeLab/Sarek#796]
Hi,
after running Sarek on whole exome sequencing data looking for somatic variants between tumor and normal cells, in the VCFTools session of the MultiQc report I get stange-looking heatmaps:
- if the input file is comparing indels or snvs of the two cell types, the value is 0 in all of the 4 regions of the graph (the whole is grey);
- if the input file contains only variants from either tumor or control cells, I only have a big squared region with the value of 0.5 (the whole is yellow).

**System:**
 - Hardware: cluster
 - Executor: slurm
 - OS: Linux Ubuntu
 - Version 18.04.02

**Nextflow:**
 - Version: 19.01.0.5050

**Container engine:**
 - Engine: Singularity
 - version: 3.0.3

**Sarek:**
 - version: dev

**Comment by MaxUlysse** [comment]
Closing due to moving to [nf-core/sarek](https://github.com/nf-core/sarek/).
If you still have the issue @silviamorins can you please open a new one on the nf-core repo?
All the best,
Maxime
