### ISSUE TITLE
fq.gz extension

### ISSUE THREAD

**Issue by apeltzer** [SciLifeLab/Sarek#797]
**Describe the bug**
When I try to analyze paired-end data with `.fq.gz` extension, this fails with a `null not found` error message.

**To Reproduce**

Use the `main.nf` on the current `dev` branch to reproduce this. Just name the files `.fq.gz`. 

**Expected behavior**
Normal run :-) 

**System (please complete the following information):**
 - Hardware: Cluster
 - Executor: Slurm
 - OS: CentOS
 - Version 7

**Nextflow (please complete the following information):**
 - Version: 19.04.0
**Container engine (please complete the following information):**
 - Engine: Singularity
 - version: 3.0.3

**Container (please complete the following information):**
 - tag: latest
**Sarek (please complete the following information):**
 - version: dev

**Additional context**

I believe this is due to the check in line 170 of `main.nf`:

```
if (SarekUtils.hasExtension(inputFile1,"fastq.gz"))
```

(should probably allow at least the `fq.gz`too) - can do a PR if you want me to do and fix this on my own 👍

**Comment by MaxUlysse** [comment]
As you prefer, I think it's a simple fix, I can do it fast

**Comment by apeltzer** [comment]
Then if you want to have a go :-)
