### ISSUE TITLE
RunVCFTools and RunBcftoolsStats are run twice for the same input

### ISSUE THREAD

**Issue by alneberg** [SciLifeLab/Sarek#802]
**Describe the bug**
RunVCFTools and RunBcftoolsStats are run both within germlineVC and annotation. From what I understand this is on the same input. Additionally, RunVCFTools is extremely slow for the gvcf file (almost 4 hours). See attached image of the timeline for germlineVC using tools Manta, Strelka and HaplotypeCaller.

![Screen Shot 2019-05-16 at 11 16 42](https://user-images.githubusercontent.com/1250075/57842105-250aa880-77cc-11e9-983a-2b9d66b31c30.png)

I don't know if the best solution is to save this for annotation only perhaps? The benefit of having it in annotation is that it can be ran in parallel with the annotation processes instead of hogging up the analysis as it is currently.

**Sarek (please complete the following information):**
 - version: 2.3.FIX1

**Comment by MaxUlysse** [comment]
OK, so I'll disable VCF tools for g.vcf
Do you want that for 2.3.FIX2, 2.4 or 2.5 ?

**Comment by MaxUlysse** [comment]
Done on [nf-core/sarek](https://github.com/nf-core/sarek)
