### ISSUE TITLE
Error executing process ConcatVCF

### ISSUE THREAD

**Issue by silviamorins** [SciLifeLab/Sarek#806]
I am running `nextflow run scilifelab/sarek/somaticVC.nf -r dev` with `--tools strelka,mutect2`, and I bump into this error:
```
Error report: Error executing process > 'ConcatVCF (MuTect2_[...]_Tumor_vs_[...]_Blood)'

Caused by:
  Process `ConcatVCF (MuTect2_[...]_Tumor_vs_[...]_Blood)` terminated with an error exit status (141)

Command executed:

  concatenateVCFs.sh -i human_g1k_v37_decoy.fasta.fai -c 10 -o MuTect2_[...]_Tumor_vs_[...]_Blood.vcf

Command exit status:
  141

Command output:
  (empty)
```
both the `.command.log` and `.command.err` in the corresponding working directory are empty. I am not sure what is going on

**System (please complete the following information):**
 - Hardware: Cluster
 - Executor: slurm
 - OS: Linux Ubuntu
 - Version 18.04

**Nextflow (please complete the following information):**
 - Version: 19.01.0

**Container engine (please complete the following information):**
 - Engine: Singularity
 - version: 3.0.3

**Sarek (please complete the following information):**
 - version: dev

**Comment by MaxUlysse** [comment]
Is this WES or WGS?

**Comment by silviamorins** [comment]
WES

**Comment by MaxUlysse** [comment]
Did you provide a targetBed?
Are all the vcf to be merged in this work directory containing variants, or are they empty?

**Comment by silviamorins** [comment]
As far as I know no, I didn't, but I might not know what it means.
All of the files contain variants, or at least the heather (I found one that does not report any variant in that particular chromosome region).

**Comment by silviamorins** [comment]
Update: I ran the germline analysis again, in case it provided a wrong/incomplete output. It cached all the process and never started any computing, but submitting the somatic analysis afterwards completed with no errors. I can't really tell where the problem was though.

**Comment by MaxUlysse** [comment]
OK, good news then ;-)
I'll try if I can figure out anything regarding that matter.
In the meanwhile, I'll close this issue

**Comment by MaxUlysse** [comment]
Now I remember what this `exit code 141` is about, it's a `SIGPIPE`.
Usually you should have this:
```nextflow
process {
  withName:ConcatVCF {
    // For unknown reasons, ConcatVCF sometimes fails with SIGPIPE
    // (exit code 141). Rerunning the process will usually work.
    errorStrategy = {task.exitStatus == 141 ? 'retry' : 'terminate'}
  }
}
```
in the base config fail, that should ensure relaunch of this process when failed with this exit code.
No idea why it faild in your case, but I'll keep that in mind.

**Comment by silviamorins** [comment]
Thanks. Indeed, the process was relaunched the last time that I (successfully) ran `somaticVC.nf`.
