### ISSUE TITLE
Huge problem with pipeline on Happlotype caller

### ISSUE THREAD

**Issue by kokyriakidis** [SciLifeLab/Sarek#807]
Running the pipeline with singularity, either on hg38 or hg19, gets wrong vcf files. I get only a few SNPs on specific chromosomes (e.g. 10 SNPs on chr4).

I get this behaviour either using wgs interval list or using target exome file.

I am running -r dev.

The command is:
```
nextflow run SciLifeLab/Sarek/main.nf \
--sampleDir /home/kokyriakidis/Desktop/TRIOS/data/178F/PROBAND \
-profile singularity  \
--genome_base /home/kokyriakidis/Desktop/TRIOS/hg19bundle \
--genome GRCh37 \
-c /home/kokyriakidis/Desktop/TRIOS/resources.config \
--max_cpus 20 \
--max_memory 50.G -r dev

nextflow run SciLifeLab/Sarek/germlineVC.nf \
--sample Preprocessing/Recalibrated/recalibrated.tsv \
-profile singularity \
--genome_base /home/kokyriakidis/Desktop/TRIOS/hg19bundle \
--genome GRCh37 \
--tools HaplotypeCaller \
-c /home/kokyriakidis/Desktop/TRIOS/resources.config \
--max_cpus 20 \
--max_memory 50.G \
--targetBED /home/kokyriakidis/Desktop/TRIOS/exome_hg19.bed -r dev
```

Running the same commands with the same files and same data 2 months ago gave the correct results!

EDIT: The MASTER branch WORKS FINE!! 

Any thoughts???

**Comment by MaxUlysse** [comment]
Closing due to moving to [nf-core/sarek](https://github.com/nf-core/sarek/).
If you still have the issue @kokyriakidis  can you please open a new one on the nf-core repo?
All the best,
Maxime
