### ISSUE TITLE
ASCAT loci for download link timeout

### ISSUE THREAD

**Issue by DoaneAS** [SciLifeLab/Sarek#809]
**Describe the bug**
 The url for the ASCTA loci file for GRCh38 as posted in the documentation appears to be dead.  
https://export.uppmax.uu.se/b2015110/caw-references/b37/1000G_phase3_20130502_SNP_maf0.3.loci.tar.bz2

**To Reproduce**
1.
 ```
aria2c https://export.uppmax.uu.se/b2015110/caw-references/b37/1000G_phase3_20130502_SNP_maf0.3.loci.tar.bz2
```

2. See error **Please provide your error message**

```
[#4be9a9 0B/0B CN:1 DL:0B]
08/04 02:13:44 [ERROR] CUID#7 - Download aborted. URI=https://export.uppmax.uu.se/b2015110/caw-references/b37/1000G_phase3_20130502_SNP_maf0.3.loci.tar.bz2
Exception: [AbstractCommand.cc:340] errorCode=2 Timeout.
```

**Expected behavior**

**System (please complete the following information):**
 - Hardware: [e.g. HPC, Desktop, Cloud...]
 - Executor: [e.g. slurm, local, awsbatch...]
 - OS: [e.g. CentOS Linux, macOS, Linux Mint...]
 - Version [e.g. 7, 10.13.6, 18.3...]

**Nextflow (please complete the following information):**
 - Version: [e.g. 0.31.0]

**Container engine (please complete the following information):**
 - Engine: [e.g. Conda, Docker or Singularity]
 - version: [e.g. 1.0.0]

**Container (please complete the following information):**
 - tag: [e.g. 1.0.0]

**Sarek (please complete the following information):**
 - version: [e.g. 2.1.0]

**Additional context**

**Comment by MaxUlysse** [comment]
Hi @DoaneAS 
Thanks a lot for your interest in this project.

We're currently porting this pipeline into the [nf-core](https://nf-co.re/) organisation: https://github.com/nf-core/sarek

The file you're interested in is at: https://export.uppmax.uu.se/sllstore2017079/Sarek/1000G_phase3_20130502_SNP_maf0.3.loci.gc

I'll update the documentation (cf #810)

Thanks again for finding and reporting this issue.
All the best,
Maxime

**Comment by DoaneAS** [comment]
Thank you @MaxUlysse, much appreciated!

And yes, I'm a big fan of [nf-core](https://nf-co.re/), and helped a little with the ATAC-seq pipeline awhile back.
