### ISSUE TITLE
No variants IDs annotated

### ISSUE THREAD

**Issue by silviamorins** [SciLifeLab/Sarek#812]
Hi,
this is not really a bug but more a hint: I have performed germline and somatic calls analysis with Sarek, running also the `annotate.nf` script, and the resulting `.vcf` files don't contain any variant ID annotated - I don't think this should be the case, as I see plenty of them in, for instance, `dbsnp_138.b37.vcf`.

**To Reproduce**
1. Command line 'nextflow run scilifelab/sarek/annotate.nf -r dev -profile cfc  --genome 'GRCh37' --annotateTools strelka --tools snpeff'

**Expected behavior**
I expect the `.vcf` files to contain variant IDs in the respective column: instead of this, it is filled with dots.

**System (please complete the following information):**
 - Hardware: Cloud
 - Executor: slurm
 - OS: Linux
 - Version 18.04

**Nextflow :**
 - Version: 19.01.0

**Container engine (please complete the following information):**
 - Engine: Singularity
 - version: 3.0.3

**Sarek (please complete the following information):**
 - version: 2.3

**Comment by MaxUlysse** [comment]
Closing due to moving to [nf-core/sarek](https://github.com/nf-core/sarek/).
If you still have the issue @silviamorins can you please open a new one on the nf-core repo?
All the best,
Maxime
