### ISSUE TITLE
error running the test

### ISSUE THREAD

**Issue by egenomics** [SciLifeLab/Sarek#815]
Hi,
I am trying to use sarek in a local workstation. After installing singularity and docker, and pulling the Sarek-test I obtain the following error when I try to execute it:

**jl@lynx:/soft/Sarek-test$ nextflow run build.nf --outDir References/smallGRCh37   --refDir Sarek-data/reference --tag latest   -profile singularity**

N E X T F L O W  ~  version 19.10.0
Launching `build.nf` [sad_boyd] - revision: 4b1f23a848
WARN: Access to undefined parameter `verbose` -- Initialise it to a default value eg. `params.verbose = some_value`
WARN: Access to undefined parameter `containers` -- Initialise it to a default value eg. `params.containers = some_value`
    ____        _____               _    
  .' _  `.     / ____|             | |   
 /  |\`-_ \   | (___  ___  _ __ __ | | __
|   | \  `-|   \___ \/__ \| ´__/ _\| |/ /
 \ |   \  /    ____) | __ | | |  __|   < 
  `|____\'    |_____/\____|_|  \__/|_|\_\
Sarek - Workflow For Somatic And Germline Variations ~ 2.3 - 4b1f23a848
Command Line: nextflow run build.nf --outDir References/smallGRCh37 --refDir Sarek-data/reference --tag latest -profile singularity
Project Dir : /soft/Sarek-test
Launch Dir  : /soft/Sarek-test
Work Dir    : /soft/Sarek-test/work
Out Dir     : References/smallGRCh37
Genome      : smallGRCh37
Containers
Repository   : docker://maxulysse
WARN: Access to undefined parameter `containerPath` -- Initialise it to a default value eg. `params.containerPath = some_value`
ContainerPath: null
Tag          : latest
[-        ] process > BuildWithDocker     -
[-        ] process > PullToSingularity   -
[-        ] process > PushToDocker        -
[-        ] process > DecompressFile      -
[-        ] process > BuildBWAindexes     -
[-        ] process > BuildReferenceIndex -
[-        ] process > BuildSAMToolsIndex  -
[-        ] process > BuildVCFIndex       -
[-        ] process > BuildCache_snpEff   -
[-        ] process > BuildWithDocker     -
[-        ] process > PullToSingularity   -
[-        ] process > PushToDocker        -
[-        ] process > DecompressFile      -
[-        ] process > BuildBWAindexes     -
[-        ] process > BuildReferenceIndex -
[-        ] process > BuildSAMToolsIndex  -
[-        ] process > BuildVCFIndex       -
[-        ] process > BuildCache_snpEff   -
[-        ] process > BuildCache_VEP      -
[-        ] process > DownloadCADD        -
Pulling Singularity image docker://maxulysse/sarek:latest [cache /home/jl/.singularity/maxulysse-sarek-latest.img]
N E X T F L O W  ~  version 19.10.0 5170
Sarek - Workflow For Somatic And Germline Variations ~ 2.3 - 4b1f23a848
Workflow execution stopped with the following message:
null
N E X T F L O W  ~  version 19.10.0 5170
Sarek - Workflow For Somatic And Germline Variations ~ 2.3 - 4b1f23a848
Command Line: nextflow run build.nf --outDir References/smallGRCh37 --refDir Sarek-data/reference --tag latest -profile singularity
Project Dir : /soft/Sarek-test
Launch Dir  : /soft/Sarek-test
Work Dir    : /soft/Sarek-test/work
Out Dir     : References/smallGRCh37
Genome      : smallGRCh37
Containers
Repository   : docker://maxulysse
ContainerPath: null
Tag          : latest
Completed at: 2020-01-02T16:33:48.201923+01:00
Duration    : 3s
Success     : false
Exit status : null
Error report: Error executing process > 'DecompressFile (Mills_and_1000G_gold_standard.indels.b37.small.vcf.gz)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name maxulysse-sarek-latest.img docker://maxulysse/sarek:latest > /dev/null
  status : 1
  message:
    WARNING: pull for Docker Hub is not guaranteed to produce the
    WARNING: same image on repeated pull. Use Singularity Registry
    WARNING: (shub://) to pull exactly equivalent images.
    ERROR MANIFEST_UNKNOWN: manifest unknown
    ERROR: pulling container failed!
WARN: Access to undefined parameter `snpEff_cache` -- Initialise it to a default value eg. `params.snpEff_cache = some_value`
WARN: Access to undefined parameter `cadd_version` -- Initialise it to a default value eg. `params.cadd_version = some_value`
WARN: Access to undefined parameter `vep_cache` -- Initialise it to a default value eg. `params.vep_cache = some_value`
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'DecompressFile (Mills_and_1000G_gold_standard.indels.b37.small.vcf.gz)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name maxulysse-sarek-latest.img docker://maxulysse/sarek:latest > /dev/null
  status : 1
  message:
    WARNING: pull for Docker Hub is not guaranteed to produce the
    WARNING: same image on repeated pull. Use Singularity Registry
    WARNING: (shub://) to pull exactly equivalent images.
    ERROR MANIFEST_UNKNOWN: manifest unknown
    ERROR: pulling container failed!

If I try to run the command that fails alone:

**jl@lynx:/soft/Sarek-test$ singularity pull  --name maxulysse-sarek-latest.img docker://maxulysse/sarek:latest**
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/maxulysse/sarek:latest
ERROR MANIFEST_UNKNOWN: manifest unknown
Cleaning up...
ERROR: pulling container failed!

**Comment by MaxUlysse** [comment]
Hi,
I'm sorry, I'm on vacation and have a less than reliable connection.

We recently ported sarek to nf-core: https://github.com/nf-core/sarek so I'll recommend you have a look at it. There are lots of improvement.

But if you still want to use this version I'll recommend using --tag 2.3 or 2.3FIX1 instead.

All the best,
Maxime

**Comment by egenomics** [comment]
Hi,
Good, I will try that one :)
However I have a question, why singularity was prefered before nf-core and now docker is favoured?

Best,
JL

**Comment by apeltzer** [comment]
Hi JL!

the profiles in the nf-core version should load Singularity and pull the Docker Image, giving you the same behaviour. In other words, we only store the Docker Image but users can use both Docker directly or Singularity that can convert the docker image "on-the-fly" to a Singularity container without you noticing 👍

**Comment by MaxUlysse** [comment]
@egenomics Any luck with nf-core/sarek?
